// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.sql

package db

import (
	"context"
	"database/sql"
)

const assignBelegbild = `-- name: AssignBelegbild :exec
UPDATE belegbilder SET beleg_id = ?, seite = ? WHERE id = ?
`

type AssignBelegbildParams struct {
	BelegID interface{}
	Seite   interface{}
	ID      string
}

func (q *Queries) AssignBelegbild(ctx context.Context, arg AssignBelegbildParams) error {
	_, err := q.db.ExecContext(ctx, assignBelegbild, arg.BelegID, arg.Seite, arg.ID)
	return err
}

const countBlobKey = `-- name: CountBlobKey :one
SELECT COUNT(*) FROM belegbilder WHERE blob_key = ? OR thumb_blob_key = ?
`

type CountBlobKeyParams struct {
	BlobKey      string
	ThumbBlobKey string
}

func (q *Queries) CountBlobKey(ctx context.Context, arg CountBlobKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobKey, arg.BlobKey, arg.ThumbBlobKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLockedMonths = `-- name: CountLockedMonths :one
SELECT COUNT(*) FROM monate
WHERE monat >= ? AND monat <= ? AND status IN ('gesperrt', 'geaendert')
`

type CountLockedMonthsParams struct {
	Monat   string
	Monat_2 string
}

func (q *Queries) CountLockedMonths(ctx context.Context, arg CountLockedMonthsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLockedMonths, arg.Monat, arg.Monat_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllSitzungen = `-- name: DeleteAllSitzungen :exec
DELETE FROM sitzungen
`

func (q *Queries) DeleteAllSitzungen(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSitzungen)
	return err
}

const deleteExpiredSitzungen = `-- name: DeleteExpiredSitzungen :exec
DELETE FROM sitzungen WHERE laeuft_ab_am <= ? OR zuletzt_aktiv_am <= ?
`

type DeleteExpiredSitzungenParams struct {
	LaeuftAbAm     string
	ZuletztAktivAm string
}

func (q *Queries) DeleteExpiredSitzungen(ctx context.Context, arg DeleteExpiredSitzungenParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSitzungen, arg.LaeuftAbAm, arg.ZuletztAktivAm)
	return err
}

const deleteOtherSitzungen = `-- name: DeleteOtherSitzungen :exec
DELETE FROM sitzungen WHERE token_hash != ?
`

func (q *Queries) DeleteOtherSitzungen(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSitzungen, tokenHash)
	return err
}

const deleteSitzung = `-- name: DeleteSitzung :exec
DELETE FROM sitzungen WHERE token_hash = ?
`

func (q *Queries) DeleteSitzung(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSitzung, tokenHash)
	return err
}

const deleteUnassignedBelegbild = `-- name: DeleteUnassignedBelegbild :execresult
DELETE FROM belegbilder WHERE id = ? AND beleg_id IS NULL
`

func (q *Queries) DeleteUnassignedBelegbild(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUnassignedBelegbild, id)
}

const findDuplicateBild = `-- name: FindDuplicateBild :one
SELECT b.id, b.datum
FROM belegbilder i
JOIN belege b ON b.id = i.beleg_id
WHERE b.geloescht_am IS NULL
  AND (?1 = '' OR b.id != ?1)
  AND (i.sha256 = ?2 OR i.upload_sha256 = ?3)
LIMIT 1
`

type FindDuplicateBildParams struct {
	ExcludeID    interface{}
	Sha256       string
	UploadSha256 string
}

type FindDuplicateBildRow struct {
	ID    string
	Datum string
}

func (q *Queries) FindDuplicateBild(ctx context.Context, arg FindDuplicateBildParams) (FindDuplicateBildRow, error) {
	row := q.db.QueryRowContext(ctx, findDuplicateBild, arg.ExcludeID, arg.Sha256, arg.UploadSha256)
	var i FindDuplicateBildRow
	err := row.Scan(&i.ID, &i.Datum)
	return i, err
}

const getBeleg = `-- name: GetBeleg :one
SELECT id, datum, mahlzeit, bezugsort, arbeitsort, haendler_name, haendler_ort, belegbetrag_cent, korrigierter_betrag_cent, korrektur_grund, notiz, quelle, version, erstellt_am, geaendert_am, geloescht_am, loesch_grund FROM belege WHERE id = ? AND geloescht_am IS NULL
`

func (q *Queries) GetBeleg(ctx context.Context, id string) (Belege, error) {
	row := q.db.QueryRowContext(ctx, getBeleg, id)
	var i Belege
	err := row.Scan(
		&i.ID,
		&i.Datum,
		&i.Mahlzeit,
		&i.Bezugsort,
		&i.Arbeitsort,
		&i.HaendlerName,
		&i.HaendlerOrt,
		&i.BelegbetragCent,
		&i.KorrigierterBetragCent,
		&i.KorrekturGrund,
		&i.Notiz,
		&i.Quelle,
		&i.Version,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.GeloeschtAm,
		&i.LoeschGrund,
	)
	return i, err
}

const getBelegByDatum = `-- name: GetBelegByDatum :one
SELECT id, datum, mahlzeit, bezugsort, arbeitsort, haendler_name, haendler_ort, belegbetrag_cent, korrigierter_betrag_cent, korrektur_grund, notiz, quelle, version, erstellt_am, geaendert_am, geloescht_am, loesch_grund FROM belege WHERE datum = ? AND geloescht_am IS NULL
`

func (q *Queries) GetBelegByDatum(ctx context.Context, datum string) (Belege, error) {
	row := q.db.QueryRowContext(ctx, getBelegByDatum, datum)
	var i Belege
	err := row.Scan(
		&i.ID,
		&i.Datum,
		&i.Mahlzeit,
		&i.Bezugsort,
		&i.Arbeitsort,
		&i.HaendlerName,
		&i.HaendlerOrt,
		&i.BelegbetragCent,
		&i.KorrigierterBetragCent,
		&i.KorrekturGrund,
		&i.Notiz,
		&i.Quelle,
		&i.Version,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.GeloeschtAm,
		&i.LoeschGrund,
	)
	return i, err
}

const getBelegbild = `-- name: GetBelegbild :one
SELECT id, beleg_id, seite, blob_key, thumb_blob_key, sha256, upload_sha256, mime, bytes, breite, hoehe, erkennung_status, erkennung_ergebnis, erkennung_roh, erkennung_fehler, erkennung_modell, erkennung_dauer_ms, erstellt_am FROM belegbilder WHERE id = ?
`

func (q *Queries) GetBelegbild(ctx context.Context, id string) (Belegbilder, error) {
	row := q.db.QueryRowContext(ctx, getBelegbild, id)
	var i Belegbilder
	err := row.Scan(
		&i.ID,
		&i.BelegID,
		&i.Seite,
		&i.BlobKey,
		&i.ThumbBlobKey,
		&i.Sha256,
		&i.UploadSha256,
		&i.Mime,
		&i.Bytes,
		&i.Breite,
		&i.Hoehe,
		&i.ErkennungStatus,
		&i.ErkennungErgebnis,
		&i.ErkennungRoh,
		&i.ErkennungFehler,
		&i.ErkennungModell,
		&i.ErkennungDauerMs,
		&i.ErstelltAm,
	)
	return i, err
}

const getEinstellungen = `-- name: GetEinstellungen :one
SELECT id, arbeitnehmer_name, personalnummer, arbeitgeber_name, standard_bezugsort,
       standard_arbeitsort, erkennung_aktiv, export_zip_standard, export_csv_standard, geaendert_am
FROM einstellungen
WHERE id = 1
`

func (q *Queries) GetEinstellungen(ctx context.Context) (Einstellungen, error) {
	row := q.db.QueryRowContext(ctx, getEinstellungen)
	var i Einstellungen
	err := row.Scan(
		&i.ID,
		&i.ArbeitnehmerName,
		&i.Personalnummer,
		&i.ArbeitgeberName,
		&i.StandardBezugsort,
		&i.StandardArbeitsort,
		&i.ErkennungAktiv,
		&i.ExportZipStandard,
		&i.ExportCsvStandard,
		&i.GeaendertAm,
	)
	return i, err
}

const getJahresregel = `-- name: GetJahresregel :one
SELECT jahr, zuschuss_cent, mahlzeiten, standard_mahlzeit, sbw_fruehstueck_cent, sbw_mittag_cent, sbw_abend_cent, hoechstzuschuss_aufschlag_cent, pauschalierung, pauschsteuersatz_bp, soli_satz_bp, gehaltsumwandlung, bundesland, kist_satz_bp, eigenanteil_variante, monatslimit, limit_modus, eigene_feiertage, notiz, erstellt_am, geaendert_am FROM jahresregeln WHERE jahr = ?
`

func (q *Queries) GetJahresregel(ctx context.Context, jahr int64) (Jahresregeln, error) {
	row := q.db.QueryRowContext(ctx, getJahresregel, jahr)
	var i Jahresregeln
	err := row.Scan(
		&i.Jahr,
		&i.ZuschussCent,
		&i.Mahlzeiten,
		&i.StandardMahlzeit,
		&i.SbwFruehstueckCent,
		&i.SbwMittagCent,
		&i.SbwAbendCent,
		&i.HoechstzuschussAufschlagCent,
		&i.Pauschalierung,
		&i.PauschsteuersatzBp,
		&i.SoliSatzBp,
		&i.Gehaltsumwandlung,
		&i.Bundesland,
		&i.KistSatzBp,
		&i.EigenanteilVariante,
		&i.Monatslimit,
		&i.LimitModus,
		&i.EigeneFeiertage,
		&i.Notiz,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const getMonat = `-- name: GetMonat :one
SELECT monat, status, gesperrt_am, letzte_exportversion FROM monate WHERE monat = ?
`

func (q *Queries) GetMonat(ctx context.Context, monat string) (Monate, error) {
	row := q.db.QueryRowContext(ctx, getMonat, monat)
	var i Monate
	err := row.Scan(
		&i.Monat,
		&i.Status,
		&i.GesperrtAm,
		&i.LetzteExportversion,
	)
	return i, err
}

const getSitzung = `-- name: GetSitzung :one
SELECT token_hash, akteur, erstellt_am, zuletzt_aktiv_am, laeuft_ab_am, user_agent, ip, oidc_id_token
FROM sitzungen
WHERE token_hash = ?
`

func (q *Queries) GetSitzung(ctx context.Context, tokenHash string) (Sitzungen, error) {
	row := q.db.QueryRowContext(ctx, getSitzung, tokenHash)
	var i Sitzungen
	err := row.Scan(
		&i.TokenHash,
		&i.Akteur,
		&i.ErstelltAm,
		&i.ZuletztAktivAm,
		&i.LaeuftAbAm,
		&i.UserAgent,
		&i.Ip,
		&i.OidcIDToken,
	)
	return i, err
}

const insertBeleg = `-- name: InsertBeleg :exec
INSERT INTO belege (
    id, datum, mahlzeit, bezugsort, arbeitsort, haendler_name, haendler_ort,
    belegbetrag_cent, korrigierter_betrag_cent, korrektur_grund, notiz, quelle,
    version, erstellt_am, geaendert_am, geloescht_am, loesch_grund
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    1, ?, ?, NULL, NULL
)
`

type InsertBelegParams struct {
	ID                     string
	Datum                  string
	Mahlzeit               string
	Bezugsort              string
	Arbeitsort             string
	HaendlerName           string
	HaendlerOrt            string
	BelegbetragCent        int64
	KorrigierterBetragCent sql.NullInt64
	KorrekturGrund         sql.NullString
	Notiz                  string
	Quelle                 string
	ErstelltAm             string
	GeaendertAm            string
}

func (q *Queries) InsertBeleg(ctx context.Context, arg InsertBelegParams) error {
	_, err := q.db.ExecContext(ctx, insertBeleg,
		arg.ID,
		arg.Datum,
		arg.Mahlzeit,
		arg.Bezugsort,
		arg.Arbeitsort,
		arg.HaendlerName,
		arg.HaendlerOrt,
		arg.BelegbetragCent,
		arg.KorrigierterBetragCent,
		arg.KorrekturGrund,
		arg.Notiz,
		arg.Quelle,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	return err
}

const insertBelegbild = `-- name: InsertBelegbild :exec
INSERT INTO belegbilder (
    id, beleg_id, seite, blob_key, thumb_blob_key, sha256, upload_sha256,
    mime, bytes, breite, hoehe, erkennung_status, erstellt_am
) VALUES (
    ?, NULL, NULL, ?, ?, ?, ?,
    'image/jpeg', ?, ?, ?, ?, ?
)
`

type InsertBelegbildParams struct {
	ID              string
	BlobKey         string
	ThumbBlobKey    string
	Sha256          string
	UploadSha256    string
	Bytes           int64
	Breite          int64
	Hoehe           int64
	ErkennungStatus string
	ErstelltAm      string
}

func (q *Queries) InsertBelegbild(ctx context.Context, arg InsertBelegbildParams) error {
	_, err := q.db.ExecContext(ctx, insertBelegbild,
		arg.ID,
		arg.BlobKey,
		arg.ThumbBlobKey,
		arg.Sha256,
		arg.UploadSha256,
		arg.Bytes,
		arg.Breite,
		arg.Hoehe,
		arg.ErkennungStatus,
		arg.ErstelltAm,
	)
	return err
}

const insertSitzung = `-- name: InsertSitzung :exec
INSERT INTO sitzungen (
    token_hash, akteur, erstellt_am, zuletzt_aktiv_am, laeuft_ab_am, user_agent, ip, oidc_id_token
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSitzungParams struct {
	TokenHash      string
	Akteur         string
	ErstelltAm     string
	ZuletztAktivAm string
	LaeuftAbAm     string
	UserAgent      string
	Ip             string
	OidcIDToken    string
}

func (q *Queries) InsertSitzung(ctx context.Context, arg InsertSitzungParams) error {
	_, err := q.db.ExecContext(ctx, insertSitzung,
		arg.TokenHash,
		arg.Akteur,
		arg.ErstelltAm,
		arg.ZuletztAktivAm,
		arg.LaeuftAbAm,
		arg.UserAgent,
		arg.Ip,
		arg.OidcIDToken,
	)
	return err
}

const latestExportAm = `-- name: LatestExportAm :one
SELECT erstellt_am, version FROM monatsexporte
WHERE monat = ?
ORDER BY version DESC
LIMIT 1
`

type LatestExportAmRow struct {
	ErstelltAm string
	Version    int64
}

func (q *Queries) LatestExportAm(ctx context.Context, monat string) (LatestExportAmRow, error) {
	row := q.db.QueryRowContext(ctx, latestExportAm, monat)
	var i LatestExportAmRow
	err := row.Scan(&i.ErstelltAm, &i.Version)
	return i, err
}

const listBelegbilderByBeleg = `-- name: ListBelegbilderByBeleg :many
SELECT id, beleg_id, seite, blob_key, thumb_blob_key, sha256, upload_sha256, mime, bytes, breite, hoehe, erkennung_status, erkennung_ergebnis, erkennung_roh, erkennung_fehler, erkennung_modell, erkennung_dauer_ms, erstellt_am FROM belegbilder WHERE beleg_id = ? ORDER BY seite ASC
`

func (q *Queries) ListBelegbilderByBeleg(ctx context.Context, belegID interface{}) ([]Belegbilder, error) {
	rows, err := q.db.QueryContext(ctx, listBelegbilderByBeleg, belegID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Belegbilder
	for rows.Next() {
		var i Belegbilder
		if err := rows.Scan(
			&i.ID,
			&i.BelegID,
			&i.Seite,
			&i.BlobKey,
			&i.ThumbBlobKey,
			&i.Sha256,
			&i.UploadSha256,
			&i.Mime,
			&i.Bytes,
			&i.Breite,
			&i.Hoehe,
			&i.ErkennungStatus,
			&i.ErkennungErgebnis,
			&i.ErkennungRoh,
			&i.ErkennungFehler,
			&i.ErkennungModell,
			&i.ErkennungDauerMs,
			&i.ErstelltAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBelegeByMonat = `-- name: ListBelegeByMonat :many
SELECT id, datum, mahlzeit, bezugsort, arbeitsort, haendler_name, haendler_ort, belegbetrag_cent, korrigierter_betrag_cent, korrektur_grund, notiz, quelle, version, erstellt_am, geaendert_am, geloescht_am, loesch_grund FROM belege
WHERE geloescht_am IS NULL AND datum >= ? AND datum < ?
ORDER BY datum ASC
`

type ListBelegeByMonatParams struct {
	Datum   string
	Datum_2 string
}

func (q *Queries) ListBelegeByMonat(ctx context.Context, arg ListBelegeByMonatParams) ([]Belege, error) {
	rows, err := q.db.QueryContext(ctx, listBelegeByMonat, arg.Datum, arg.Datum_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Belege
	for rows.Next() {
		var i Belege
		if err := rows.Scan(
			&i.ID,
			&i.Datum,
			&i.Mahlzeit,
			&i.Bezugsort,
			&i.Arbeitsort,
			&i.HaendlerName,
			&i.HaendlerOrt,
			&i.BelegbetragCent,
			&i.KorrigierterBetragCent,
			&i.KorrekturGrund,
			&i.Notiz,
			&i.Quelle,
			&i.Version,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.GeloeschtAm,
			&i.LoeschGrund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErkennungen = `-- name: ListErkennungen :many
SELECT b.id, b.datum, b.haendler_name, b.belegbetrag_cent, i.erkennung_ergebnis
FROM belege b
JOIN belegbilder i ON i.beleg_id = b.id
WHERE b.geloescht_am IS NULL
  AND i.erkennung_ergebnis IS NOT NULL
  AND (?1 = '' OR b.id != ?1)
`

type ListErkennungenRow struct {
	ID                string
	Datum             string
	HaendlerName      string
	BelegbetragCent   int64
	ErkennungErgebnis interface{}
}

func (q *Queries) ListErkennungen(ctx context.Context, excludeID interface{}) ([]ListErkennungenRow, error) {
	rows, err := q.db.QueryContext(ctx, listErkennungen, excludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListErkennungenRow
	for rows.Next() {
		var i ListErkennungenRow
		if err := rows.Scan(
			&i.ID,
			&i.Datum,
			&i.HaendlerName,
			&i.BelegbetragCent,
			&i.ErkennungErgebnis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExporte = `-- name: ListExporte :many
SELECT id, monat, version, erstellt_am, csv_blob_key, zip_blob_key
FROM monatsexporte
WHERE monat = ?
ORDER BY version ASC
`

type ListExporteRow struct {
	ID         string
	Monat      string
	Version    int64
	ErstelltAm string
	CsvBlobKey interface{}
	ZipBlobKey interface{}
}

func (q *Queries) ListExporte(ctx context.Context, monat string) ([]ListExporteRow, error) {
	rows, err := q.db.QueryContext(ctx, listExporte, monat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExporteRow
	for rows.Next() {
		var i ListExporteRow
		if err := rows.Scan(
			&i.ID,
			&i.Monat,
			&i.Version,
			&i.ErstelltAm,
			&i.CsvBlobKey,
			&i.ZipBlobKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJahresregeln = `-- name: ListJahresregeln :many
SELECT jahr, zuschuss_cent, mahlzeiten, standard_mahlzeit, sbw_fruehstueck_cent, sbw_mittag_cent, sbw_abend_cent, hoechstzuschuss_aufschlag_cent, pauschalierung, pauschsteuersatz_bp, soli_satz_bp, gehaltsumwandlung, bundesland, kist_satz_bp, eigenanteil_variante, monatslimit, limit_modus, eigene_feiertage, notiz, erstellt_am, geaendert_am FROM jahresregeln ORDER BY jahr
`

func (q *Queries) ListJahresregeln(ctx context.Context) ([]Jahresregeln, error) {
	rows, err := q.db.QueryContext(ctx, listJahresregeln)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jahresregeln
	for rows.Next() {
		var i Jahresregeln
		if err := rows.Scan(
			&i.Jahr,
			&i.ZuschussCent,
			&i.Mahlzeiten,
			&i.StandardMahlzeit,
			&i.SbwFruehstueckCent,
			&i.SbwMittagCent,
			&i.SbwAbendCent,
			&i.HoechstzuschussAufschlagCent,
			&i.Pauschalierung,
			&i.PauschsteuersatzBp,
			&i.SoliSatzBp,
			&i.Gehaltsumwandlung,
			&i.Bundesland,
			&i.KistSatzBp,
			&i.EigenanteilVariante,
			&i.Monatslimit,
			&i.LimitModus,
			&i.EigeneFeiertage,
			&i.Notiz,
			&i.ErstelltAm,
			&i.GeaendertAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitzungen = `-- name: ListSitzungen :many
SELECT token_hash, akteur, erstellt_am, zuletzt_aktiv_am, laeuft_ab_am, user_agent, ip, oidc_id_token
FROM sitzungen
ORDER BY zuletzt_aktiv_am DESC
`

func (q *Queries) ListSitzungen(ctx context.Context) ([]Sitzungen, error) {
	rows, err := q.db.QueryContext(ctx, listSitzungen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sitzungen
	for rows.Next() {
		var i Sitzungen
		if err := rows.Scan(
			&i.TokenHash,
			&i.Akteur,
			&i.ErstelltAm,
			&i.ZuletztAktivAm,
			&i.LaeuftAbAm,
			&i.UserAgent,
			&i.Ip,
			&i.OidcIDToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedBelegbilderBefore = `-- name: ListUnassignedBelegbilderBefore :many
SELECT id, beleg_id, seite, blob_key, thumb_blob_key, sha256, upload_sha256, mime, bytes, breite, hoehe, erkennung_status, erkennung_ergebnis, erkennung_roh, erkennung_fehler, erkennung_modell, erkennung_dauer_ms, erstellt_am FROM belegbilder WHERE beleg_id IS NULL AND erstellt_am < ?
`

func (q *Queries) ListUnassignedBelegbilderBefore(ctx context.Context, erstelltAm string) ([]Belegbilder, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedBelegbilderBefore, erstelltAm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Belegbilder
	for rows.Next() {
		var i Belegbilder
		if err := rows.Scan(
			&i.ID,
			&i.BelegID,
			&i.Seite,
			&i.BlobKey,
			&i.ThumbBlobKey,
			&i.Sha256,
			&i.UploadSha256,
			&i.Mime,
			&i.Bytes,
			&i.Breite,
			&i.Hoehe,
			&i.ErkennungStatus,
			&i.ErkennungErgebnis,
			&i.ErkennungRoh,
			&i.ErkennungFehler,
			&i.ErkennungModell,
			&i.ErkennungDauerMs,
			&i.ErstelltAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGesperrtGeaendert = `-- name: MarkGesperrtGeaendert :exec
UPDATE monate
SET status = 'geaendert'
WHERE monat >= ? AND monat <= ? AND status = 'gesperrt'
`

type MarkGesperrtGeaendertParams struct {
	Monat   string
	Monat_2 string
}

func (q *Queries) MarkGesperrtGeaendert(ctx context.Context, arg MarkGesperrtGeaendertParams) error {
	_, err := q.db.ExecContext(ctx, markGesperrtGeaendert, arg.Monat, arg.Monat_2)
	return err
}

const softDeleteBeleg = `-- name: SoftDeleteBeleg :execresult
UPDATE belege
SET geloescht_am = ?,
    loesch_grund = ?,
    version = version + 1,
    geaendert_am = ?
WHERE id = ? AND version = ? AND geloescht_am IS NULL
`

type SoftDeleteBelegParams struct {
	GeloeschtAm sql.NullString
	LoeschGrund sql.NullString
	GeaendertAm string
	ID          string
	Version     int64
}

func (q *Queries) SoftDeleteBeleg(ctx context.Context, arg SoftDeleteBelegParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteBeleg,
		arg.GeloeschtAm,
		arg.LoeschGrund,
		arg.GeaendertAm,
		arg.ID,
		arg.Version,
	)
}

const touchSitzung = `-- name: TouchSitzung :exec
UPDATE sitzungen SET zuletzt_aktiv_am = ? WHERE token_hash = ?
`

type TouchSitzungParams struct {
	ZuletztAktivAm string
	TokenHash      string
}

func (q *Queries) TouchSitzung(ctx context.Context, arg TouchSitzungParams) error {
	_, err := q.db.ExecContext(ctx, touchSitzung, arg.ZuletztAktivAm, arg.TokenHash)
	return err
}

const unassignBelegbild = `-- name: UnassignBelegbild :exec
UPDATE belegbilder SET beleg_id = NULL, seite = NULL WHERE id = ?
`

func (q *Queries) UnassignBelegbild(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, unassignBelegbild, id)
	return err
}

const updateBeleg = `-- name: UpdateBeleg :execresult
UPDATE belege
SET datum = ?,
    mahlzeit = ?,
    bezugsort = ?,
    arbeitsort = ?,
    haendler_name = ?,
    haendler_ort = ?,
    belegbetrag_cent = ?,
    korrigierter_betrag_cent = ?,
    korrektur_grund = ?,
    notiz = ?,
    quelle = ?,
    version = version + 1,
    geaendert_am = ?
WHERE id = ? AND version = ? AND geloescht_am IS NULL
`

type UpdateBelegParams struct {
	Datum                  string
	Mahlzeit               string
	Bezugsort              string
	Arbeitsort             string
	HaendlerName           string
	HaendlerOrt            string
	BelegbetragCent        int64
	KorrigierterBetragCent sql.NullInt64
	KorrekturGrund         sql.NullString
	Notiz                  string
	Quelle                 string
	GeaendertAm            string
	ID                     string
	Version                int64
}

func (q *Queries) UpdateBeleg(ctx context.Context, arg UpdateBelegParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBeleg,
		arg.Datum,
		arg.Mahlzeit,
		arg.Bezugsort,
		arg.Arbeitsort,
		arg.HaendlerName,
		arg.HaendlerOrt,
		arg.BelegbetragCent,
		arg.KorrigierterBetragCent,
		arg.KorrekturGrund,
		arg.Notiz,
		arg.Quelle,
		arg.GeaendertAm,
		arg.ID,
		arg.Version,
	)
}

const updateEinstellungen = `-- name: UpdateEinstellungen :exec
UPDATE einstellungen
SET arbeitnehmer_name = ?,
    personalnummer = ?,
    arbeitgeber_name = ?,
    standard_bezugsort = ?,
    standard_arbeitsort = ?,
    erkennung_aktiv = ?,
    export_zip_standard = ?,
    export_csv_standard = ?,
    geaendert_am = ?
WHERE id = 1
`

type UpdateEinstellungenParams struct {
	ArbeitnehmerName   string
	Personalnummer     string
	ArbeitgeberName    string
	StandardBezugsort  string
	StandardArbeitsort string
	ErkennungAktiv     int64
	ExportZipStandard  int64
	ExportCsvStandard  int64
	GeaendertAm        string
}

func (q *Queries) UpdateEinstellungen(ctx context.Context, arg UpdateEinstellungenParams) error {
	_, err := q.db.ExecContext(ctx, updateEinstellungen,
		arg.ArbeitnehmerName,
		arg.Personalnummer,
		arg.ArbeitgeberName,
		arg.StandardBezugsort,
		arg.StandardArbeitsort,
		arg.ErkennungAktiv,
		arg.ExportZipStandard,
		arg.ExportCsvStandard,
		arg.GeaendertAm,
	)
	return err
}

const upsertJahresregel = `-- name: UpsertJahresregel :exec
INSERT INTO jahresregeln (
    jahr, zuschuss_cent, mahlzeiten, standard_mahlzeit,
    sbw_fruehstueck_cent, sbw_mittag_cent, sbw_abend_cent, hoechstzuschuss_aufschlag_cent,
    pauschalierung, pauschsteuersatz_bp, soli_satz_bp, gehaltsumwandlung,
    bundesland, kist_satz_bp, eigenanteil_variante, monatslimit, limit_modus,
    eigene_feiertage, notiz, erstellt_am, geaendert_am
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
ON CONFLICT (jahr) DO UPDATE SET
    zuschuss_cent = excluded.zuschuss_cent,
    mahlzeiten = excluded.mahlzeiten,
    standard_mahlzeit = excluded.standard_mahlzeit,
    sbw_fruehstueck_cent = excluded.sbw_fruehstueck_cent,
    sbw_mittag_cent = excluded.sbw_mittag_cent,
    sbw_abend_cent = excluded.sbw_abend_cent,
    hoechstzuschuss_aufschlag_cent = excluded.hoechstzuschuss_aufschlag_cent,
    pauschalierung = excluded.pauschalierung,
    pauschsteuersatz_bp = excluded.pauschsteuersatz_bp,
    soli_satz_bp = excluded.soli_satz_bp,
    gehaltsumwandlung = excluded.gehaltsumwandlung,
    bundesland = excluded.bundesland,
    kist_satz_bp = excluded.kist_satz_bp,
    eigenanteil_variante = excluded.eigenanteil_variante,
    monatslimit = excluded.monatslimit,
    limit_modus = excluded.limit_modus,
    eigene_feiertage = excluded.eigene_feiertage,
    notiz = excluded.notiz,
    geaendert_am = excluded.geaendert_am
`

type UpsertJahresregelParams struct {
	Jahr                         int64
	ZuschussCent                 int64
	Mahlzeiten                   string
	StandardMahlzeit             string
	SbwFruehstueckCent           int64
	SbwMittagCent                int64
	SbwAbendCent                 int64
	HoechstzuschussAufschlagCent int64
	Pauschalierung               int64
	PauschsteuersatzBp           int64
	SoliSatzBp                   int64
	Gehaltsumwandlung            int64
	Bundesland                   string
	KistSatzBp                   int64
	EigenanteilVariante          string
	Monatslimit                  int64
	LimitModus                   string
	EigeneFeiertage              string
	Notiz                        string
	ErstelltAm                   string
	GeaendertAm                  string
}

func (q *Queries) UpsertJahresregel(ctx context.Context, arg UpsertJahresregelParams) error {
	_, err := q.db.ExecContext(ctx, upsertJahresregel,
		arg.Jahr,
		arg.ZuschussCent,
		arg.Mahlzeiten,
		arg.StandardMahlzeit,
		arg.SbwFruehstueckCent,
		arg.SbwMittagCent,
		arg.SbwAbendCent,
		arg.HoechstzuschussAufschlagCent,
		arg.Pauschalierung,
		arg.PauschsteuersatzBp,
		arg.SoliSatzBp,
		arg.Gehaltsumwandlung,
		arg.Bundesland,
		arg.KistSatzBp,
		arg.EigenanteilVariante,
		arg.Monatslimit,
		arg.LimitModus,
		arg.EigeneFeiertage,
		arg.Notiz,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	return err
}

const upsertMonatStatus = `-- name: UpsertMonatStatus :exec
INSERT INTO monate (monat, status, gesperrt_am, letzte_exportversion)
VALUES (?, ?, ?, ?)
ON CONFLICT (monat) DO UPDATE SET
    status = excluded.status,
    gesperrt_am = COALESCE(monate.gesperrt_am, excluded.gesperrt_am)
`

type UpsertMonatStatusParams struct {
	Monat               string
	Status              string
	GesperrtAm          interface{}
	LetzteExportversion int64
}

func (q *Queries) UpsertMonatStatus(ctx context.Context, arg UpsertMonatStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonatStatus,
		arg.Monat,
		arg.Status,
		arg.GesperrtAm,
		arg.LetzteExportversion,
	)
	return err
}
