// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :execresult
UPDATE jobs
SET status = 'laeuft',
    versuche = versuche + 1,
    geaendert_am = ?
WHERE id = ? AND status = 'wartend'
`

type ClaimJobParams struct {
	GeaendertAm string
	ID          string
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimJob, arg.GeaendertAm, arg.ID)
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs WHERE status = ?
`

func (q *Queries) CountJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenJobsByPayload = `-- name: CountOpenJobsByPayload :one
SELECT COUNT(*) FROM jobs
WHERE typ = ? AND payload = ? AND status IN ('wartend', 'laeuft')
`

type CountOpenJobsByPayloadParams struct {
	Typ     string
	Payload string
}

func (q *Queries) CountOpenJobsByPayload(ctx context.Context, arg CountOpenJobsByPayloadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenJobsByPayload, arg.Typ, arg.Payload)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJob = `-- name: GetJob :one
SELECT id, typ, payload, status, versuche, naechster_versuch_am, ergebnis, fehler, erstellt_am, geaendert_am
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Typ,
		&i.Payload,
		&i.Status,
		&i.Versuche,
		&i.NaechsterVersuchAm,
		&i.Ergebnis,
		&i.Fehler,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (
    id, typ, payload, status, versuche, naechster_versuch_am, erstellt_am, geaendert_am
) VALUES (
    ?, ?, ?, 'wartend', 0, ?, ?, ?
)
`

type InsertJobParams struct {
	ID                 string
	Typ                string
	Payload            string
	NaechsterVersuchAm string
	ErstelltAm         string
	GeaendertAm        string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Typ,
		arg.Payload,
		arg.NaechsterVersuchAm,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	return err
}

const listErkennungOffen = `-- name: ListErkennungOffen :many
SELECT id FROM belegbilder
WHERE erkennung_status IN ('ausstehend', 'laeuft')
`

func (q *Queries) ListErkennungOffen(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listErkennungOffen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWaitingJob = `-- name: NextWaitingJob :one
SELECT id, typ, payload, status, versuche, naechster_versuch_am, ergebnis, fehler, erstellt_am, geaendert_am
FROM jobs
WHERE status = 'wartend' AND naechster_versuch_am <= ?
ORDER BY naechster_versuch_am ASC, erstellt_am ASC
LIMIT 1
`

func (q *Queries) NextWaitingJob(ctx context.Context, naechsterVersuchAm string) (Job, error) {
	row := q.db.QueryRowContext(ctx, nextWaitingJob, naechsterVersuchAm)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Typ,
		&i.Payload,
		&i.Status,
		&i.Versuche,
		&i.NaechsterVersuchAm,
		&i.Ergebnis,
		&i.Fehler,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const resetLaufendeErkennung = `-- name: ResetLaufendeErkennung :exec
UPDATE belegbilder
SET erkennung_status = 'ausstehend'
WHERE erkennung_status = 'laeuft'
`

func (q *Queries) ResetLaufendeErkennung(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetLaufendeErkennung)
	return err
}

const resetRunningJobs = `-- name: ResetRunningJobs :exec
UPDATE jobs
SET status = 'wartend',
    geaendert_am = ?
WHERE status = 'laeuft'
`

func (q *Queries) ResetRunningJobs(ctx context.Context, geaendertAm string) error {
	_, err := q.db.ExecContext(ctx, resetRunningJobs, geaendertAm)
	return err
}

const saveErkennungVersuch = `-- name: SaveErkennungVersuch :exec
UPDATE belegbilder
SET erkennung_roh = ?,
    erkennung_modell = ?,
    erkennung_dauer_ms = ?
WHERE id = ?
`

type SaveErkennungVersuchParams struct {
	ErkennungRoh     interface{}
	ErkennungModell  interface{}
	ErkennungDauerMs interface{}
	ID               string
}

func (q *Queries) SaveErkennungVersuch(ctx context.Context, arg SaveErkennungVersuchParams) error {
	_, err := q.db.ExecContext(ctx, saveErkennungVersuch,
		arg.ErkennungRoh,
		arg.ErkennungModell,
		arg.ErkennungDauerMs,
		arg.ID,
	)
	return err
}

const setBelegbildErkennung = `-- name: SetBelegbildErkennung :exec
UPDATE belegbilder
SET erkennung_status = ?,
    erkennung_ergebnis = ?,
    erkennung_roh = ?,
    erkennung_fehler = ?,
    erkennung_modell = ?,
    erkennung_dauer_ms = ?
WHERE id = ?
`

type SetBelegbildErkennungParams struct {
	ErkennungStatus   string
	ErkennungErgebnis interface{}
	ErkennungRoh      interface{}
	ErkennungFehler   interface{}
	ErkennungModell   interface{}
	ErkennungDauerMs  interface{}
	ID                string
}

func (q *Queries) SetBelegbildErkennung(ctx context.Context, arg SetBelegbildErkennungParams) error {
	_, err := q.db.ExecContext(ctx, setBelegbildErkennung,
		arg.ErkennungStatus,
		arg.ErkennungErgebnis,
		arg.ErkennungRoh,
		arg.ErkennungFehler,
		arg.ErkennungModell,
		arg.ErkennungDauerMs,
		arg.ID,
	)
	return err
}

const setErkennungStatus = `-- name: SetErkennungStatus :exec
UPDATE belegbilder
SET erkennung_status = ?,
    erkennung_fehler = ?
WHERE id = ?
`

type SetErkennungStatusParams struct {
	ErkennungStatus string
	ErkennungFehler interface{}
	ID              string
}

func (q *Queries) SetErkennungStatus(ctx context.Context, arg SetErkennungStatusParams) error {
	_, err := q.db.ExecContext(ctx, setErkennungStatus, arg.ErkennungStatus, arg.ErkennungFehler, arg.ID)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET status = ?,
    naechster_versuch_am = ?,
    ergebnis = ?,
    fehler = ?,
    geaendert_am = ?
WHERE id = ?
`

type UpdateJobParams struct {
	Status             string
	NaechsterVersuchAm string
	Ergebnis           interface{}
	Fehler             interface{}
	GeaendertAm        string
	ID                 string
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Status,
		arg.NaechsterVersuchAm,
		arg.Ergebnis,
		arg.Fehler,
		arg.GeaendertAm,
		arg.ID,
	)
	return err
}
