// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"
)

const getSystemValue = `-- name: GetSystemValue :one
SELECT value FROM system WHERE key = ?
`

func (q *Queries) GetSystemValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSystemValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSystemValue = `-- name: UpsertSystemValue :exec
INSERT INTO system (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type UpsertSystemValueParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertSystemValue(ctx context.Context, arg UpsertSystemValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemValue, arg.Key, arg.Value)
	return err
}
